### ISSUE TITLE
RFC: Make bencode `abstract-encoding` compliant

### ISSUE THREAD

**Issue by jhermsmeier** [themasch/node-bencode#37]
There's [abstract-encoding](https://github.com/mafintosh/abstract-encoding) - which seems very reasonable to me - makes it a lot easier to just swap out modules without anything else needing adjustment. Thoughts?

**Comment by themasch** [comment]
:+1: looks like this could be done without much changes. Would you suggest a simple wrapper or would you change node-bencode to better fit the abstract-encoding api?

**Comment by jhermsmeier** [comment]
I'd prefer changing `node-bencode`'s API to comply with `abstract-encoding` - which would bump the major on this I guess...

**Comment by fanatid** [comment]
:+1: please check [varstruct](https://github.com/dominictarr/varstruct) (I think you find this package useful!)
Any ideas how you can handle streams with `abstract-encoding`? (related: https://github.com/themasch/node-bencode/issues/7)

**Comment by jhermsmeier** [comment]
Closed by #43
