### ISSUE TITLE
Invalid Delimiter

### ISSUE THREAD

**Issue by bennesp** [themasch/node-bencode#45]
I'm trying to decode a file, and I'm getting this error:
`Error: Invalid data: Missing delimiter ":" [0x3a]`
But this site http://marquisdegeek.com/code_bencode.php and others node-js decoder managed to decode the file.

Examples of file that generate the above error:

[Ubuntu Iso Torrent](https://github.com/themasch/node-bencode/files/204803/ubuntu-15.10-desktop-amd64.iso.zip)
[Tracker Announce Response](https://github.com/themasch/node-bencode/files/204805/announce.2.zip)

**Comment by jhermsmeier** [comment]
I just ran a quick decode with the current version (`bencode@0.9`) on the files you supplied, and haven't gotten an error (see below) – could you provide more detail about the environment and versions used (OS, node version, npm and package version)?

```
$ node bin/bencode.js test/ubuntu-15.10-desktop-amd64.iso.torrent
Dict {
  announce: <Buffer 68 74 74 70 3a 2f 2f 74 6f 72 72 65 6e 74 2e 75 62 75 6e 74 75 2e 63 6f 6d 3a 36 39 36 39 2f 61 6e 6e 6f 75 6e 63 65>,
  'announce-list':
   [ [ <Buffer 68 74 74 70 3a 2f 2f 74 6f 72 72 65 6e 74 2e 75 62 75 6e 74 75 2e 63 6f 6d 3a 36 39 36 39 2f 61 6e 6e 6f 75 6e 63 65> ],
     [ <Buffer 68 74 74 70 3a 2f 2f 69 70 76 36 2e 74 6f 72 72 65 6e 74 2e 75 62 75 6e 74 75 2e 63 6f 6d 3a 36 39 36 39 2f 61 6e 6e 6f 75 6e 63 65> ] ],
  comment: <Buffer 55 62 75 6e 74 75 20 43 44 20 72 65 6c 65 61 73 65 73 2e 75 62 75 6e 74 75 2e 63 6f 6d>,
  'creation date': 1445507299,
  info:
   Dict {
     length: 1178386432,
     name: <Buffer 75 62 75 6e 74 75 2d 31 35 2e 31 30 2d 64 65 73 6b 74 6f 70 2d 61 6d 64 36 34 2e 69 73 6f>,
     'piece length': 524288,
     pieces: <Buffer 69 9a 2d d8 22 ea 5e b2 5c d4 e4 48 c5 e8 0e 53 ba d5 b1 6c ec 0e 71 a7 55 53 77 fd dd 17 f3 08 be 96 ad 6f f8 ff 4a b3 9b 50 83 0b 49 49 59 64 b9 a9 ... > } }
```

**Comment by bennesp** [comment]
Where can I find bin/bencode.js ? Currently I'm executing this:

```
fs.readFile('ubuntu-15.10-desktop-amd64.iso.torrent', 'binary', (err,data) => {
  if(err){console.log(err);return;}
  else {console.log(bencode.decode(data));}
});
```

I'm using the current version of bencode package (0.9), node v4.2.1, npm 2.14.7 on Linux

Thanks for your time

**Comment by jhermsmeier** [comment]
The problem with what you're doing is the `'binary'` encoding – which really is `latin-1`, not the 'binary' one would expect, as you can read in [node's buffer character encoding documentation](https://nodejs.org/api/buffer.html#buffer_buffers_and_character_encodings).

If you omit the encoding, `fs.readFile()` will give you a raw buffer, instead of encoding it to a `latin-1` encoded string, which will work perfectly fine with `bencode.decode()`.

You can also make it work with the `'binary'` encoding by telling `bencode.decode()` the encoding of your string, like so:

```js
bencode.decode( data, 'binary' )
```

And `bin/bencode.js` is just something I just wrote to test this, it's essentially
```js
var path = require( 'path' )
var fs = require( 'fs' )
var util = require( 'util' )
var bencode = require( '..' )

var argv = process.argv.slice( 2 )
var filename = path.resolve( process.cwd(), argv.shift() )
var file = fs.readFileSync( filename )

console.log( bencode.decode( file ) )
```

**Comment by bennesp** [comment]
Well, it works actually.
Thanks for the help and sorry for wasting your time!

**Comment by jhermsmeier** [comment]
No worries, glad I could help (and that it wasn't a bug)!
