### ISSUE TITLE
Decode breaks for compact format

### ISSUE THREAD

**Issue by vaibhav-walia** [themasch/node-bencode#54]
Hi Guys,

When a tracker response contains peer list in the compact format [(BEP23),](http://www.bittorrent.org/beps/bep_0023.html) decode breaks giving the following error : Invalid data: Missing delimiter ":" [0x3a]

For example decode fails on the response of [this](http://legittorrents.info:2710/announce?info_hash=4%00tO%87y%ae%1b%e7%f4g%87%e8!%2b%b6%3f%ee%f3V&peer_id=-VT0001-000000000000&port=6687&uploaded=0&downloaded=0&left=207984&event=started) request .

Is this supported, or am I doing something wrong ?

Version : 0.10.0
OS : Ubuntu 14.04.3 LTS

**Comment by jhermsmeier** [comment]
Interesting. I just added a test with the announce from the URL you specified – and I couldn't get it to fail. Was that indeed the announce URL it failed on?

Also, can you reproduce that error?
And could you maybe share how you request & decode that response, or a stack trace?

My current guess would be that it blew up due to a partial response, or additional bytes somewhere – but that's just a wild guess really.

```
  should be able to handle an compacted peer announce

    { complete: 4,
      incomplete: 3,
      interval: 1800,
      'min interval': 1800,
      peers: <Buffer 2e bd 1b 64 1a 1f 51 d5 4c 05 46 cc 34 21 90 40 1a 1f 62 6e e9 c6 c8 d5 cb 0d 92 13 1a 1f ac 4e 68 9a 3c 6b 18 0f 3d 57 46 db> }
    ✔ should be equivalent

  should be able to handle an compacted peer announce when decoding strings

    { complete: 4,
      incomplete: 3,
      interval: 1800,
      'min interval': 1800,
      peers: '.�\u001bd\u001a\u001fQ�L\u0005F�4!�@\u001a\u001fbn�����\r�\u0013\u001a\u001f�Nh�<k\u0018\u000f=WF�' }
    ✔ should be equivalent

```

I'll try and collect some more announces for testing later, and see if I can also grab a real-world uncompacted one to add to the tests.

**Comment by vaibhav-walia** [comment]
Hi Jonas,

I'm still able to reproduce this error.
Have a look at [this](https://runkit.com/vaibhav-walia/bencode-decode-error)

**Comment by jhermsmeier** [comment]
I see – the issue is that the response body is not a Buffer, since it's converted to a String by the `request` module. You'll need to set `encoding: null` in the request options to have the body returned as a buffer (as stated in `request`'s docs), and then it should work:

```js
var benc = require( 'bencode' );
var request = require( 'request' );

request({
  url: 'http://legittorrents.info:2710/announce?info_hash=4%00tO%87y%ae%1b%e7%f4g%87%e8!%2b%b6%3f%ee%f3V&peer_id=-VT0001-000000000000&port=6687&uploaded=0&downloaded=0&left=207984&event=started',
  method: 'GET',
  encoding: null,
}, function( error, response, body ) {
  if ( error ) {
    console.log( error );
  } else {
    console.log( response.body );
    var decodedBody = benc.decode( response.body );
    console.log( decodedBody );
    console.log( typeof( decodedBody.peers ) );
  }
});
```

**Comment by vaibhav-walia** [comment]
Hi Jonas,

Valid point, I tried the encoding option and it seems to work.
Thank you for your time and help!
