### ISSUE TITLE
browserify not work

### ISSUE THREAD

**Issue by zunsthy** [themasch/node-bencode#63]
Because of browser's polyfill, `Buffer` is object and will be considered as dictionary when`bencode.encode`.

example:
```javascript
const data = { error: Uint8Array.from([101, 114, 114, 111, 114]) }
const result = bencode.encode(data)
console.log(result)
```
The expected result is `d5:error5:errore`, but the real result is `d5:errordi0e:i101ei1e:i114e...`.

```javascript
  switch (typeof data) {
    case 'string':
      encode.buffer(buffers, data)
      break
    case 'number':
      encode.number(buffers, data)
      break
    case 'object':
      data.constructor === Array
        ? encode.list(buffers, data)
        : encode.dict(buffers, data)
      break
    case 'boolean':
      encode.number(buffers, data ? 1 : 0)
      break
  }
```
`typeof` will return 'object' for `Buffer`, if browser's polyfill works.

**Comment by themasch** [comment]
Sorry that it took that long. 

I'm not an expert with browserify and I'm not really sure on how we could fix this. 
Detecting "Uint8Array" and handle it as an buffer seems to be wrong for cases where people actually want it to be an array of ints. We can't check for valid utf-8 chars anyway. 

Personally I'd tend to say "We don't care about browserify, fix this in 'userland'." But thats not the best way to handle it I guess. 

@jhermsmeier any ideas on this?

**Comment by jhermsmeier** [comment]
Well, I guess we should check for typed arrays with `value.buffer instanceof ArrayBuffer` and then at least handle them as lists, not dicts.

Thinking about it, @feross might have run into similar issues with this in WebTorrent?

I'll explore this further later today.

**Comment by feross** [comment]
@jhermsmeier In WebTorrent, we're careful to not pass in Buffer properties to `bencode.encode`.

Right now, `Buffer` is being treated like a dictionary, which doesn't make sense.  A good solution to this problem is to treat a `Buffer` like a string. You can detect a buffer with `Buffer.isBuffer()`, then call `buffer.toString()`. Or, treating them like arrays is reasonable too.

**Comment by jimmywarting** [comment]
could #64 close this issue now?

**Comment by feross** [comment]
> could #64 close this issue now?

Looks like it.

**Comment by themasch** [comment]
Oh, yeah, great!
