### ISSUE TITLE
Update perfomance test

### ISSUE THREAD

**Issue by reklatsmasters** [themasch/node-bencode#67]
I wrote a bit faster bencode parser [btparse](https://www.npmjs.com/package/btparse). Please update perfomance test in readme.

**Comment by slang800** [comment]
looks like it is faster:

```
                      decode to buffer
          51,532 op/s » bencode
          43,908 op/s » bencoding
          36,990 op/s » dht-bencode
           2,053 op/s » bncode
          67,397 op/s » btparse
          24,695 op/s » dht.js
```

...this is just a quick test on my AMD box, not the Intel Core i7-5500U that I ran the last bench on, but that does look promising.

**Comment by themasch** [comment]
wow, nice numbers there. Great work @reklatsmasters! 
Created a PR for the updated benchmark, please comment #72 if you want to change something (order or appearance etc.)
