### ISSUE TITLE
Release v1.0.0

### ISSUE THREAD

**Issue by feross** [themasch/node-bencode#74]
This library is stable and depended-upon by lots of packages. Want to just call it 1.0.0?

Sidenote: semver is weird for versions below 1.0.0, so the new recommendation is to start packages off at 1.0.0 instead of 0.0.0.

**Comment by jhermsmeier** [comment]
Yeah, might want to get https://github.com/themasch/node-bencode/pull/75 in before, and then make it v1.0.0, @themasch?

**Comment by themasch** [comment]
merge #75, go 1.0! sounds good!

**Comment by themasch** [comment]
Thanks for the kick in the butt, @feross. 1.0 was long overdue
