### ISSUE TITLE
When is the release of version 2.0.1?

### ISSUE THREAD

**Issue by pinghe** [themasch/node-bencode#85]
When is the release of version 2.0.1, I'm particularly interested in the bug that fix deprecation warning on 'Buffer()' constructor

**Comment by themasch** [comment]
sorry for the long delay. I just released it. As far as I can see the latest changes (since 2.0.0) should indeed only require a patch release since there should be no api break whatsoever. Thanks for the reminder, even if it took several months for me to follow.

**Comment by pinghe** [comment]
Thanks.
